services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7744:7744"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production  # Cambiar el valor de NODE_ENV
